"""s

Revision ID: e886a45848d8
Revises: 8d5490b628f7
Create Date: 2024-01-25 14:15:23.695728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e886a45848d8'
down_revision = '8d5490b628f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=140),
               existing_nullable=False)
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('about_me',
               existing_type=sa.String(length=140),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
